version: "3.9"

volumes:
  storage_data:

services:

  react:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    restart: always